version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: students-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./backend/users.db:/app/users.db
    environment:
      - DATABASE_URL=sqlite:///./users.db

  frontend:
    build:
      context: ./front
    container_name: students-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 